### PR TITLE
create one template for all resource deployment

### PR DESCRIPTION
**Pull request by Akash-Ramgoolam**
New template SchoolAccountArm.json created, all resources to be deployed from one template

### CODE REVIEW

**Review by sagajadfe — CHANGES_REQUESTED** [review]
@Akash-Ramgoolam As discussed this PR need to be rejected and create new PR with new ARM template you have experimented.

**Comment by Akash-Ramgoolam** [comment]
Write Powershell script to create Resource group and Run template from cli. Write ARM template in one file to provisioned the resources in Azure portal. No more linked

**Comment by Akash-Ramgoolam** [comment]
Added powershell script to create RG in azure portal, script to provision Azure portal locally from powershell cli. Deployment of resources from one template(schoolaccountArm.json)

**Review by kruncher — APPROVED** [review]
Looks good to me.

**Pull request merged**
